[package]
name = "marinade-sdk"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marinade_sdk"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["cpi"]

[profile.release]
overflow-checks = true

[dependencies]
solana-program = "1.9.17"
spl-token = "3.1.1"
borsh = "0.9.3"
